# Generated by Django 5.2 on 2025-07-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_client_adresse_client_codepostal_client_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montantTTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='montantTVA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='tauxTVA',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
