# Generated by Django 5.2 on 2025-07-22 11:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_facture_montantttc_facture_montanttva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montantTTC',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montantTVA',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tauxTVA',
            field=models.DecimalField(choices=[(Decimal('0.00'), '0 %'), (Decimal('5.50'), '5.5 %'), (Decimal('10.00'), '10 %'), (Decimal('20.00'), '20 %')], decimal_places=2, default=Decimal('20.00'), max_digits=5),
        ),
    ]
