# Generated by Django 5.2 on 2025-07-22 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_alter_facture_montantttc_alter_facture_montanttva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factures.facture')),
            ],
        ),
    ]
