# Generated by Django 5.2 on 2025-07-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_facturecreationlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactureCreationLog',
            new_name='FactureLog',
        ),
    ]
